fix spaces -> tabs

diff --git a/aports/main/libsamsung-ipc/APKBUILD b/aports/main/libsamsung-ipc/APKBUILD
--- a/aports/main/libsamsung-ipc/APKBUILD
+++ b/aports/main/libsamsung-ipc/APKBUILD
@@ -30,26 +30,26 @@ prepare() {
 
 	cd "$builddir"
 
-    local _patch_failed=
+	local _patch_failed=
 
-    # first apply patches in specified order
-    for i in $source; do
-        case $i in
-            *.patch)
-            msg "Applying $i..."
-            if ! patch -s -p1 -N -i "$srcdir"/$i; then
-                echo $i >>failed
-                    _patch_failed=1
-            fi
-            ;;
-        esac
-    done
+	# first apply patches in specified order
+	for i in $source; do
+		case $i in
+			*.patch)
+			msg "Applying $i..."
+			if ! patch -s -p1 -N -i "$srcdir"/$i; then
+				echo $i >>failed
+					_patch_failed=1
+			fi
+			;;
+		esac
+	done
 
-    if ! [ -z "$_patch_failed" ]; then
-        error "The following patches failed:"
-        cat failed
-        return 1
-    fi
+	if ! [ -z "$_patch_failed" ]; then
+		error "The following patches failed:"
+		cat failed
+		return 1
+	fi
 }
 
 sha512sums="59974fda58914829a221ecf8ce5bec5ec1e76ef1dba95d86942b224b41d3e41e542c3214be43ba31dd93304ed4aa8135892ea364dd1aa4aa42217cf20507db14  libsamsung-ipc-6.0-0002.tar.gz
